version: 1.2
workflows:
  - name: wdlHelloWorld
    subclass: WDL
    publish: true
    primaryDescriptorPath: /Dockstore.wdl
    testParameterFiles:
      - /test/dockstore.wdl.json
    authors:
      - name: Jeremy Adams
        email: jeremy.adams@ga4gh.org
        affiliation: GA4GH
    filters:
      branches:
        - main
